apiVersion: v1
kind: Service
metadata:
  name: argo-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: argo-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
      protocol: TCP

